### ISSUE TITLE
CNCF transfer: update website footer

### ISSUE THREAD

**Issue by flynnduism** [vscode-kubernetes-tools/vscode-kubernetes-tools#1015]
Part of the [tracker issue opened by the CNCF #745](https://github.com/cncf/toc/issues/745):

> Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed

The [landing page website](https://azure.github.io/vscode-kubernetes-tools/) needs to be updated to have the LF footer.

**Comment by flynnduism** [comment]
_(I will work on this item, but I cannot assign it to myself)_

**Comment by itowlson** [comment]
@flynnduism Sorry to hound you when there have been holidays and you have so much else going on, but do you know when you're likely to have bandwidth for this?  Thanks!

**Comment by lstocchi** [comment]
Closing as https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1033 fixed it
