### ISSUE TITLE
[Feature Proposal] Porter dependencies baked in Kubernetes Extension

### ISSUE THREAD

**Issue by Tatsinnit** [vscode-kubernetes-tools/vscode-kubernetes-tools#1024]
### What is the proposal?

Can I please propose to add Porter dependency for this extension, It has few benefits and I have mentioned it below. Hence the key intent of this Issue is to open a proposal for he idea to bake in Porter with this extension.

* What is Porter?
    * https://porter.sh 
    * https://porter.sh/docs/ 

### Why?

The key advantage with this will be that since Porter comes with built in Mixim we can add value for various install features using porter bundles for them.

### What will be benefits?

A key benefit I see is that it will help in minimising the number of lines of code to carefully handle the installations in the dependent extensions to be handle via one Porter Install command.

What do you guys think and I am happy to chip in effort to make this happen if all agrees.

Thank you so much ☕️🙏❤️

💡Fyi and cc: @itowlson, @carolynvs , @squillace, @lstocchi, @rzhang628 or @davefellows for thoughts\ideas.

**Comment by squillace** [comment]
Hi @Tatsinnit! While I like this, I know there's also a fledgling Porter extension: https://github.com/getporter/vscode-extension. BTW, that's already IN the CNCF as well. Much might be made, perhaps, of working with that one and layering functionality in there rather than in core. 

That's my immediate response, but I'd be interested in @itowlson's take.

**Comment by itowlson** [comment]
Yes, if the proposal is simply to add some generic Porter commands and features, then the Porter extension is the place for that.  It already has a bunch of stuff for helping with schema editing and validation, etc., so I'd build on top of that rather than adding them here.

However, if you're thinking of Kubernetes-specific features that happen to use Porter, or API infrastructure to facilitate using Porter to perform installations (as we have with Helm), then that might fit in the k8s extension.  Could you elaborate more specifically on what you're envisaging?

**Comment by Tatsinnit** [comment]
Thanks you so much to @squillace and @itowlson for this, and quick replies (this is awesome), here is what I had in mind  which generated this idea. Please let me know if I can elaborate further or missed something. 

* ah yes, something like API infrastructure like we do it with `kubectlV1`. Some version of Porter for the support like kubectl here https://github.com/Azure/vscode-kubernetes-tools-api 

Scenario I had in mind was like this:

* If we think of `aks-extension` which uses this extension for and its dependencies as piggy backing and think of feature which we have shipped in that extension like `ASO` then currently we have written code to `kubectl apply` few things and knit them together for the end result. **But** if we have `porter` api available all we will do is:

* `porterV1.invokeCommand(Porter install everything)` which just let porter to all the heavy lifting and we have end result to take care

Sorry if I am missing out anything please let me know I will add more. ❤️🙏

**Comment by itowlson** [comment]
A thought on that: does this need to be in the k8s extension itself, or could we make a NPM package that exposes a Porter wrapper, and if necessary a way to initialise that package from the k8s extension context?  That way, extensions like AKS would have easy access to the Porter commands just by adding that package, but we wouldn't need to maintain and version an API for Porter within the k8s extension (given that the k8s extension itself doesn't incorporate any Porter support).

(to be clear, I'm not trying to be discouraging, I like the idea of making it easy for extension^2s to use Porter, just thinking out loud about the best place for this to sit)

**Comment by Tatsinnit** [comment]
This is perfect guidance and discussion and yes please thinking out-loud idea will help in further clarity. Yes, agree. What I think I am not sure about how the actual internal plumbing to call the `porter` will work, i.e. for the API to work, at some stage the `porter binary` will be in need. So I wonder where will that reside. ☕️☕️

**Comment by itowlson** [comment]
I have a feeling the Porter extension defines a setting for the Porter binary, so a hypothetical NPM package could use that if present, then look on system PATH.  You could also implement an auto install similar to what the k8s extension does.

We don't have a well-bounded module that could be plucked into a new package.  I started on that with `binutilplusplus.ts` but I don't know how easy it would be to get it working standalone.  There is a small cluster of files in the Porter extension that relate to invoking external programs and specifically Porter commands: this might be easier to extract, and already does a lot of what you want, though it does not have the auto install feature.  Specifically see https://github.com/getporter/vscode-extension/blob/main/src/porter/porter.ts and the modules it depends on.

**Comment by Tatsinnit** [comment]
Closing this issue, as this was created by me as an idea, and given Porter extension already exist we can try this as dependency for the AKS cluster or new devx extension if the user-scenario fits the need. Thank you so much @itowlson and @squillace as always for discussion. Thank you!
