### ISSUE TITLE
While switching cluster in kubernetes extention laptop hangs

### ISSUE THREAD

**Issue by dtrivedi-conga** [vscode-kubernetes-tools/vscode-kubernetes-tools#1050]
Issue Type: <b>Bug</b>

When I switch to any of the listed kubernetes cluster in extension my laptop hangs and the only way to bring it back is to reboot the laptop.
Even my Microsoft Teams, Microsoft Outlook also stops responding after this.

Extension version: 1.3.7
VS Code version: Code 1.65.2 (Universal) (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 8|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id 5a4086fe-8718-48d6-870a-41c7d4940fcd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
pynewfile477:30450038

```

</details>

**Comment by itowlson** [comment]
Yikes - that's an awful bug and I'm sorry it's having such an impact on you.

That said, I don't know how it's even possible for us to hang the entire machine.  The only thing I can think of is that we're doing something that ends up consuming 100% CPU, or possibly something that spins off an "infinite" number of kubectl processes.

I don't know how much patience you'll have to investigate given the impact, but if you are able, it would be useful to know:

1. What happens to CPU usage when you switch cluster?
2. Do you see a large number of shell or kubectl processes running afterwards?
3. If you have Process Explorer open (Help > Open Process Explorer) during the switch, does it show new or CPU-heavy processes under the extension host?
4. Does this happen with all clusters, or only to clusters where you need to authenticate?  (E.g. if you have a KinD or Minikube cluster, are you able to switch to that okay?)

Thanks, and apologies again!

**Comment by mark-bradshaw** [comment]
I'm having the same issue.  When I look at the Process Explorer what I see is the extension going and pulling each of the CRDs on the cluster I'm connecting to.  That cluster has a LOT of CRDs.  I don't know what all it's doing with the CRDs, but that seems to be what it's doing when it locks the system.

**Comment by itowlson** [comment]
Ah, this sounds like it might relate to the extension suggestion feature.  @lstocchi, as an interim workaround, would your new config setting bypass the fetching of CRDs or only of putting up the suggestions message?

**Comment by lstocchi** [comment]
@itowlson no it only hides the suggestions message. But i don't think the problem is there because it just makes a call to fetch all api-versions so it should be fast. 
I guess the problem comes when we fetch all CRDs to find some custom schemas to enable a better code completion :/
Maybe we should give a way to disable it or just give the users the option to target some specific CRDs ... WDYT? @itowlson 

Many thanks for your comment @mark-bradshaw, this helps us finding the right issue :pray:

**Comment by mark-bradshaw** [comment]
I hope you can fix it.  I enjoy the extension. 

On April 12, 2022, Hugo Menzaghi ***@***.***> wrote:
> @itowlson <https://github.com/itowlson> no it only hides the
> suggestions message. But i don't think the problem is there because it
> just makes a call to fetch all api-versions so it should be fast.
>  I guess the problem comes when we fetch all CRDs to find some custom
> schemas to enable a better code completion :/
>  Maybe we should give a way to disable it or just give the users the
> option to target some specific CRDs ... WDYT? @itowlson
> <https://github.com/itowlson>
>
> Many thanks for your comment @mark-bradshaw <https://github.com/mark-
> bradshaw>, this helps us finding the right issue 🙏
>

—
Reply to this email directly, view it on GitHub
<https://github.com/vscode-kubernetes-tools/vscode-kubernetes-
tools/issues/1050#issuecomment-1096333663>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAIFQ2WIEQIVPENGFLDUKGTVEUWV5ANCNFSM5ROC56QQ>.
You are receiving this because you were mentioned.Message ID: <vscode-
kubernetes-tools/vscode-kubernetes-
***@***.***>

**Comment by lstocchi** [comment]
@mark-bradshaw could you please tell me approx. how many CRDs you have in your cluster? The one with a lot of CRDs. I am trying to figure out which should be the upper limit to use to change the plugin behavior. Thanks!

**Comment by mark-bradshaw** [comment]
220
