### ISSUE TITLE
The Kubernetes extension overrides yaml schema settings

### ISSUE THREAD

**Issue by pinkplus** [vscode-kubernetes-tools/vscode-kubernetes-tools#1054]
I'm using Argo Workflow, and configured yaml schema to point to its schema file:
```json
// .vscode/settings.json
{
    "yaml.schemas": {
        "https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/jsonschema/schema.json": "*"
    }
}
```

This is an example yaml file:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test
spec:
  ...
```

With this setting, yaml autocomplete works fine when the Kubernetes extesion is not installed. In particular, it provides detailed autocomplete for `metadata` and `spec` fields.

However, after the Kubernetes extension is installed, autocomplete doesn't work for `metadata` or `spec` field any more. VSCode says the schema is `kubernetes://schema/argoproj.io/v1alpha1@cronworkflow` instead of the one I specified in the settings. When I open the new schema, it's a very basic version specifying `metadata` and `spec` to be a plain object, which is why detailed autocomplete doesn't work.

How can I make sure the detailed autocomplete works even when the Kubernetes extension is installed?

**Comment by itowlson** [comment]
I'm afraid we buried the docs on this one.  At the moment you have to exclude it on a file-by-file basis by editing in a magic comment at the top:

https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools#yaml-processing-directives

```
# vscode-kubernetes-tools: exclude
```

**Comment by pinkplus** [comment]
Right, it’s not very obvious from the doc, but it works after I added the comment. Thanks!

**Comment by itowlson** [comment]
Thanks for closing the loop on that!  I'll close the issue since the solution works for you - please reopen if needed.
