### ISSUE TITLE
Lack of documentation (esp. launch.json and python)

### ISSUE THREAD

**Issue by TimoFriedri** [vscode-kubernetes-tools/vscode-kubernetes-tools#1064]
Hi,

Kubernetes: Debug (Attach) works for me, but then I cannot set the pathMappings which makes it useless mostly. 

How does a correct configuration looks like in the launch,json file for python? 
So could you please complete the following dummy:

```
  {
     "version": "0.2.0",
      "configurations": [
        {
            "name": "Full dummy for python attach",
            "type": "python",
            "request": "attach",
            "pipeTransport": {
                "pipeProgram": "kubectl",
                "pipeArgs": [ "exec", "-i", "${command:extension.vsKubernetesSelectPod}", "--" ],
                "pipeCwd": "${workspaceRoot}",
                "debuggerPath": "/vsdbg/vsdbg", ####### ?
                "quoteArgs": false
            },
         ##### HERE WHAT?
   }
```

Thanks a lot.

**Comment by lstocchi** [comment]
Hi @TimoFriedri, i'm not the best person to help you with Python but afair you shouldn't do anything. The plugin should create everything it needs automatically. You just need to make sure to open the right port 5678 (default one) or if you use a custom one to add it in the settings `vs-kubernetes.python-debug-port` and that you use ptvsd to attach to it.

P.S: i was looking at the ptvsd repo and i saw it is deprecated and replaced by debugpy (https://github.com/microsoft/ptvsd) so maybe this is the issue. I'm going to do some testing to verify if we need to update some code. Sorry for the trouble.
