### ISSUE TITLE
Snippets not showing in v1.3.8

### ISSUE THREAD

**Issue by Marvin-S** [vscode-kubernetes-tools/vscode-kubernetes-tools#1078]
Hello,
as of update 1.3.8 the code snippets in yaml files are not showing anymore.
If I install version 1.3.7 the snippets are displayed again.

I've installed a complete fresh vs code with only the Kubernetes and YAML extension installed.

With version 1.3.8
![Bildschirmfoto 2022-05-19 um 14 34 54](https://user-images.githubusercontent.com/52828682/169295167-c43eb509-71d0-4f16-9ba2-784eccdb72e9.png)

With version 1.3.7
![Bildschirmfoto 2022-05-19 um 14 34 24](https://user-images.githubusercontent.com/52828682/169295218-29b2fb2f-f9ed-410c-a636-3159a408ae35.png)

**Comment by lstocchi** [comment]
Thanks for opening this @Marvin-S and sorry for the trouble. We already found the source of the problem and fixed it https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1071 . In the next days we should be able to make a new release.
