### ISSUE TITLE
[Feature request] Add ability to control justMyCode dotnet debugger option

### ISSUE THREAD

**Issue by xzxzxc** [vscode-kubernetes-tools/vscode-kubernetes-tools#1083]
By default, in the dotnet debugger "justMyCode" feature is enabled. That means that the debugger will skip any optimized code (e.g. built using release configuration). In most cases, you build your code in this configuration for production. So when you are trying to debug your production code you need to disable "justMyCode". But unfortunately, at this time, there is no option to disable it when you use this extension's "Debug (Attach)" command.

It would be nice to have such an ability. For example `vs-kubernetes.dotnet-enableJustMyCode` flag in the configuration of the extension.

P.S. As a workaround you can set `"justMyCode": false` in the `launch.json` file. You can see an example of such file [here](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/blob/master/debug-on-kubernetes.md#miscellaneous-commands).

**Comment by lstocchi** [comment]
Closing it as #1086 was merged. Feel free to reopen if you face any issue. Thanks!
