### ISSUE TITLE
Minikube upgrade notification on every startup with latest beta installed

### ISSUE THREAD

**Issue by vuldin** [vscode-kubernetes-tools/vscode-kubernetes-tools#1091]
I installed the current latest minikube beta, and now I get the below notification on each startup. I think the best fix for this issue would be to have an option in settings that allows disabling this notification.

![image](https://user-images.githubusercontent.com/310946/173580963-5dc983a1-f425-49d6-9d98-8f00115fdc6f.png)

**Comment by vuldin** [comment]
Similar but different from https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/946

**Comment by lstocchi** [comment]
Hi @vuldin, there should be a setting called `checkForMinikubeUpgrade`. If set to false you should not see that notification. Could you please let us know if this fix your issue? Thanks

```
checkForMinikubeUpgrade - On extension startup, notify if a minikube upgrade is available. Defaults to true.
```

**Comment by vuldin** [comment]
Hmm I don't see this as an option in my plugin settings (`v1.3.9`):
![image](https://user-images.githubusercontent.com/310946/173591204-dc3b6097-6dd3-4e35-a83c-9141ae7adfc8.png)

**Comment by lstocchi** [comment]
You need to use the parent setting `vs-kubernetes`
![image](https://user-images.githubusercontent.com/49404737/173594689-4e861d63-88b8-43cd-9117-522afe17ad38.png)

**Comment by itowlson** [comment]
The nested ones don't show up in the GUI unfortunately - that's one of several reasons why we are gradually moving to the top-level-with-prefix settings.  Apologies for the inconvenience.

(The use of nested settings predates even me I think, and was fine at the time - but subsequent enhancements to Code have turned it into a misfeature.  But moving to a new structure is non-trivial...)

**Comment by lstocchi** [comment]
Solved. Closing it
