### ISSUE TITLE
When I use the "Logs" or "Terminal" functions of "pods", I get an error

### ISSUE THREAD

**Issue by zx472010602** [vscode-kubernetes-tools/vscode-kubernetes-tools#1107]
When I use the "Logs" or "Terminal" functions of "pods", I get an error of 
"
Failed to get containers in resource: error: error parsing jsonpath {'NAME\tIMAGE\n'}{range .spec.containers[*]}{.name}{'\t'}{.image}{'\n'}{end}, unrecognized character in action: U+0027 '''
"

**Comment by zx472010602** [comment]
![image](https://user-images.githubusercontent.com/31379313/188553392-2e120aee-a929-4986-97cf-0ab93ebba8aa.png)
![image](https://user-images.githubusercontent.com/31379313/188553568-59a578ff-d8a9-4081-95b9-069f2af866d0.png)

**Comment by lstocchi** [comment]
Hi @zx472010602 ,
the error is quite clear, there is something (`'` chars) that makes the plugin fails.
Which version of kubectl are you using? Which OS? Which kubernetes version? 

could you please run this command in your terminal and check if you have the same error?
```
## if using linux, macOS
kubectl get pod/common-kafka-0 -o jsonpath='{"NAME\tIMAGE\n"}{range .spec.containers[*]}{.name}{"\t"}{.image}{"\n"}{end}' --namespace=<your-namespace>

## if using windows
kubectl get pod/common-kafka-0 -o jsonpath="{'NAME\\tIMAGE\\n'}{range .spec.containers[*]}{.name}{'\\t'}{.image}{'\\n'}{end}" --namespace=<your-namespace>
```

Can you also send the whole output of `kubectl get pod/common-kafka-0 -n=<your-namespace> -o yaml` ?

Thanks

**Comment by zx472010602** [comment]
> 

![image](https://user-images.githubusercontent.com/31379313/189302940-f9e5b7ce-8457-460f-acc9-36fa01abc0dd.png)

**Comment by lstocchi** [comment]
Thanks @zx472010602
i downloaded your same version 1.7 and i'm able to replicate your issue, but then if i execute it with a newer kubectl it works fine.

Is there any chance you can upgrade your kubectl? Something like 1.21?
If so, please download it and test it manually
`curl -LO "https://dl.k8s.io/release/v1.21.0/bin/windows/amd64/kubectl.exe"`
If it works go to the settings.json in vscode (ctrl + shift +p -> `Preferences: Open Settings (json)) and update the path of your kubectl
```
"vs-kubernetes": {
        "vscode-kubernetes.kubectl-path.windows": new-path-here
```
This should also solve your other issue https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1108

Please let us know how it goes. Thanks!!

**Comment by zx472010602** [comment]
@lstocchi Thanks a lot, everything is back after the update
