### ISSUE TITLE
When I use the "port-forward" functions of "pods" or "service", I get an error

### ISSUE THREAD

**Issue by zx472010602** [vscode-kubernetes-tools/vscode-kubernetes-tools#1108]
error: invalid resource name "xxxxxxxxxxxxx": [may not contain '/']
![image](https://user-images.githubusercontent.com/31379313/188555115-ade9756f-0d35-4abc-b924-9dff1433a913.png)

**Comment by zx472010602** [comment]
![image](https://user-images.githubusercontent.com/31379313/188555189-4e085028-8ab5-4b0b-ba6d-724765bb0242.png)

**Comment by lstocchi** [comment]
Hello,
which version of kubectl are you using?

@itowlson you know windows better than me. Any idea?

**Comment by itowlson** [comment]
The only thing I can think of is if there has been a breaking change to `kubectl port-forward` so it now requires a syntax like `pod foo` instead of `pod/foo`.  Doesn't look like anything related to Windows...

**Comment by itowlson** [comment]
Nope, docs say `pods/foo` should be fine... https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/

**Comment by itowlson** [comment]
@zx472010602 if you type that command manually into the terminal, do you get the same error?  If not, is there another syntax you know that does work for you?

**Comment by zx472010602** [comment]
> @zx472010602如果您在终端中手动键入该命令，您是否会收到相同的错误？如果没有，您是否知道另一种语法对您有用？

手动一样会，而且CMD,powershell，gitbash,都会报一样的错误
