### ISSUE TITLE
show logs renders an empty file view

### ISSUE THREAD

**Issue by fabwamb** [vscode-kubernetes-tools/vscode-kubernetes-tools#1111]
When i click show logs
<img width="281" alt="image" src="https://user-images.githubusercontent.com/114335939/192436786-05d43c89-6c94-4432-8939-ad65d7f5d1ba.png">
A new file view is opened but is empty.
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/114335939/192436875-da143611-a4a4-4f9e-8650-88a2f86c6840.png">
 The cmd on bash shows several pages of logs
<img width="885" alt="image" src="https://user-images.githubusercontent.com/114335939/192437292-10129ae9-e051-4f5c-a8ef-be2d512cef9d.png">

**Comment by fabwamb** [comment]
Version 1.3.10
```
Webview fatal error: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
(anonymous) @ index.html?id=c241b53b-aeb7-4e63-8b4e-5936162c8a27&origin=59428196-82f5-4be3-abfb-e7b6fd17bd5a&swVersion=4&extensionId=ms-kubernetes-tools.vscode-kubernetes-tools&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:863
await in (anonymous) (async)
HostMessaging.channel.port1.onmessage @ index.html?id=c241b53b-aeb7-4e63-8b4e-5936162c8a27&origin=59428196-82f5-4be3-abfb-e7b6fd17bd5a&swVersion=4&extensionId=ms-kubernetes-tools.vscode-kubernetes-tools&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:295
notificationsAlerts.ts:42 Fehler beim Laden der Webansicht: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

**Comment by lstocchi** [comment]
@fabwamb we released a new version of the plugin last week with an update of the log viewer. Could you please see if it works for you? Thanks!! :pray:

**Comment by cforce** [comment]
Seems to work now . Tx a lot . Hopefully it stays like this as this was already the second time i had to report after it was once fixed and then later with another version broke again.
