### ISSUE TITLE
logs webview jumps back when scrolling up

### ISSUE THREAD

**Issue by C-nit** [vscode-kubernetes-tools/vscode-kubernetes-tools#1113]
The webview is a great feature to go through logs, but I encounter an annoying behavior when scrolling up in the logs. It doesn't happen when scrolling down.

Reproduce:
Open a pods logs and scroll down and up a bit. At some point the view starts to jump back repeatedly to the same position of the logs.
It also happens when using the PgUp key.

It's independent from following the logs or having that running/stopped.

**Comment by mkstephenson** [comment]
I also get this issue when new logs are being pushed to the log window which is pretty annoying for a pod that logs quite often

**Comment by lstocchi** [comment]
Sorry for the slow response guys :pray:  Gonna give it a look now

**Comment by lstocchi** [comment]
@C-nit @mkstephenson Not sure if i was able to detect and fix your same issue. If you could confirm the fix, it would be great. You can run the PR https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1129 or create a vsix from that or use the vsix I made https://github.com/lstocchi/vscode-kubernetes-tools/blob/master/vscode-kubernetes-tools-1.3.11.vsix 
Thanks again for your help!! :pray:
