### ISSUE TITLE
Logs view broken with latest VSCode Insiders

### ISSUE THREAD

**Issue by asampal** [vscode-kubernetes-tools/vscode-kubernetes-tools#1116]
Attempting to show logs for a resource opens a view in VSCode, but no buttons are shown in the UI, as seen below:

![image](https://user-images.githubusercontent.com/281639/195634504-0014744a-999c-45d3-a656-9d50e0073454.png)

Kubernetes extension version 
v1.3.10

Version: 1.73.0-insider (system setup)
Commit: a8108049ab61b970f2ec1839dfb753054e07395e
Date: 2022-10-13T05:19:31.002Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by asampal** [comment]
Now on VSCode the version below, with the k8s logs view still not functioning.

Version: 1.73.0-insider (system setup)
Commit: 1c78193f54fac6036829ec554ce218d99afc1f15
Date: 2022-10-18T07:28:31.647Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

The following commits, the first on the 13th and going back to about the 11th I'm guessing would be the most likely candidates to have broken this extension's logs view since they were all WebView related. IIRC noticed the break around the 14th/13th or so.

https://github.com/microsoft/vscode/commit/7ef8e6b87a2a5a25ba1ef946bd1640ca3510956c
https://github.com/microsoft/vscode/commit/db9f5f9b9bdd06cc037607473513b59d85617082
https://github.com/microsoft/vscode/commit/24b8eb0d548828db3de30f1a33c4dcebb460047b
https://github.com/microsoft/vscode/commit/f4c58486f4a33b8c61f30a244374ef0d27dc19c3

**Comment by lstocchi** [comment]
Thanks @asampal and sorry for the late response. Quite busy on other stuff. I'll give this a look and come back to you before the end of this week.

**Comment by asampal** [comment]
I get the following in the dev tools console. Note that my workspace is a remote one, opened against a WSL2 directory. Kubernetes (via minikube) is running in WSL2.

![image](https://user-images.githubusercontent.com/281639/197216644-61f43226-29d7-4126-8c93-9bb1714ffadd.png)

**Comment by lstocchi** [comment]
@asampal thanks for the info. I was able to replicate it 👍

**Comment by asampal** [comment]
Is there anything else i can provide?

**Comment by lstocchi** [comment]
@asampal nono, helping me to replicate the issue was good enough.

After updating the code to use the asWebviewUri method it seems working for me. Could you give that a try? https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1119

Just build it with vsce and install as vsix on your vscode in wsl 🤞 
Thank you for your help!!

**Comment by asampal** [comment]
What is vsce, @lstocchi ? VSCode?

**Comment by lstocchi** [comment]
It's a tool for packaging the extension. More at https://code.visualstudio.com/api/working-with-extensions/publishing-extension

Basically you should open the branch source code https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1119 in vscode. Install everything `npm i` then build it `npm run compile` then package it `vsce package`.
Now you should see a vsix file in the vscode-kubernetes-tools folder and you can install it on your vscode in wsl

**Comment by asampal** [comment]
Looks good, @lstocchi. When do you think you could publish it?

**Comment by asampal** [comment]
Actually, please hold on. I'm seeing very heavy CPU use from my cluster after looking at the logs. Looking into it.

**Comment by asampal** [comment]
It doesn't look like the extension had anything to do with the CPU spike. Please go ahead and publish.

**Comment by asampal** [comment]
@lstocchi , could you please publish the fixed extension?

**Comment by lstocchi** [comment]
It will be published soon. I see there are other PRs so we are going to make a release with all of them
