### ISSUE TITLE
Logs screen has no buttons rendered

### ISSUE THREAD

**Issue by Belpaire** [vscode-kubernetes-tools/vscode-kubernetes-tools#1124]
In the last version of vscode the logging screen is suddenly not working anymore (no buttons at all): 
![image](https://user-images.githubusercontent.com/17363778/199995738-d19c24a4-2b0c-428d-a5e9-958328746f93.png)
I looked in the webview console errors on what happens and this is the output when I try to get the logs of a pod:

[logserrors.txt](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/files/9939079/logserrors.txt)
![image](https://user-images.githubusercontent.com/17363778/199996431-effb75a6-06e8-4e86-a654-a0aec7b5bb6f.png)
(first one in text, second one as image in webview).

**Comment by alaytonoracle** [comment]
I have the same issue.

**Comment by lstocchi** [comment]
This error is the same as https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1116 . It was fixed and merged but still not published. If you want you can use https://github.com/lstocchi/vscode-kubernetes-tools/blob/master/vscode-kubernetes-tools-1.3.6.vsix in the meantime. I hope to publish everything beginning of next week. Sorry for the trouble

**Comment by Belpaire** [comment]
Ok, I must have missed that issue (I did a search on logging, but I must have missed it somehow). The linked vsix indeed solves the issue.
