### ISSUE TITLE
Pod logs are no longer displayed

### ISSUE THREAD

**Issue by pgallmann** [vscode-kubernetes-tools/vscode-kubernetes-tools#1126]
Since updating vsc to version 1.73.0 it is no longer possible to display the log of the selected pod after selecting a cluster / workload / pod.
The following is displayed after selecting logs to a pod:

Follow Logs:Show timestamp:Since:      Second(s)Minute(s)Hour(s)    Tail:RunResetSave Settings    Destination:WebviewTerminal
Filter:that matchthat don't matchafter matchbefore match                                Wrap lines:             Scroll To Bottom

**Comment by lstocchi** [comment]
This should be related to https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1119 . You could try the fix by installing https://github.com/lstocchi/vscode-kubernetes-tools/blob/master/vscode-kubernetes-tools-1.3.6.vsix manually.

BTW a new release is on its way https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1125 and you should see it in the marketplace in few hours.

I'll keep this open so you can confirm the fix.

**Comment by Tatsinnit** [comment]
Hiya @pgallmann and @lstocchi ❤️☕️ If it helps, I tried to replicate this and at least debug this but seems like it is bringing right set of result and it is only empty for the cases where the pod logs are genuinely empty. Sharing some analysis from my end and please correct me if anything I did wrong. cc and a gentle cc: @squillace + @itowlson 

Not able to replicate on extension k8s version: `v1.3.10` and one **Mac O/S** with **vscode** `Version: 1.73.0`.

**Steps:**

* From current cluster context, expand, --> `workloads` --> `pods` --> `right-click` on selected pod --> `select logs` (Please see screenshot below.

* Upon the appearance of the web view for see-logs, it `Run` and I can see logs.

**Under the hood**

* I can see that extension runs following kubectl under the hood:
* `kubectl logs pod/canipull --namespace=default --container=canipull` - **I wonder** - so incase it is returning the empty value for that pod might be it is returning right value? 

**Screenshots:**

<img width="327" alt="Screenshot 2022-11-09 at 8 16 01 AM" src="https://user-images.githubusercontent.com/6233295/200656149-5bb3d849-f3d0-4ec5-b843-b4edfa661ced.png">


<img width="1666" alt="Screenshot 2022-11-09 at 8 16 47 AM" src="https://user-images.githubusercontent.com/6233295/200656256-873c7e98-b1d8-4190-a4e5-1fe0dbfe8b9b.png">


<img width="1671" alt="Screenshot 2022-11-09 at 8 17 14 AM" src="https://user-images.githubusercontent.com/6233295/200656187-c4cf579f-81d3-4ae3-b9c8-01625d68ca0e.png">

**Comment by lstocchi** [comment]
Closing it as it seems to be fixed. Please let us know if you face any other problem. Thanks!!
