### ISSUE TITLE
Extension failed with `kubectl not found` while it is in the path and setting

### ISSUE THREAD

**Issue by tigerinus** [vscode-kubernetes-tools/vscode-kubernetes-tools#1132]
![image](https://user-images.githubusercontent.com/7172560/205116603-fc40398c-ffab-422f-94a9-6239832b5b06.png)

**Comment by dserodio** [comment]
I'm also having this issue.

VS Code 1.73.1
Kubernetes Extension v1.3.11
macOS 12.6.1 

I just opened my settings.json file and saw that this path is set in more than one key, and I never edited the JSON manually, only thru the extension's config panel:

```
  "vscode-kubernetes.kubectl-path.mac": "/Users/danielserodio/.asdf/shims/kubectl",
  "vscode-kubernetes.kubectl-path": "/Users/danielserodio/.asdf/shims/kubectl",
  "vs-kubernetes": {
    "vs-kubernetes.namespace": "",
    "vs-kubernetes.kubectl-path": "",
    "vs-kubernetes.helm-path": "",
    "vs-kubernetes.minikube-path": "",
    "vs-kubernetes.kubectlVersioning": "user-provided",
    "vs-kubernetes.outputFormat": "yaml",
    "vs-kubernetes.kubeconfig": "",
    "vs-kubernetes.knownKubeconfigs": [],
    "vs-kubernetes.autoCleanupOnDebugTerminate": false,
    "vs-kubernetes.nodejs-autodetect-remote-root": true,
    "vs-kubernetes.nodejs-remote-root": "",
    "vs-kubernetes.nodejs-debug-port": 9229,
    "vs-kubernetes.dotnet-vsdbg-path": "~/vsdbg/vsdbg",
    "vs-kubernetes.local-tunnel-debug-provider": "",
    "checkForMinikubeUpgrade": true,
    "imageBuildTool": "Docker"
  }
```

**Comment by Tatsinnit** [comment]
❤️☕️ Thank you so much for this issue @tigerinus and @dserodio , here is what I have noticed and try to replicate and to me this seems like incorrect setting path, I was able to replicates this only if `vscode-kubernetes.kubectl-path` and `vscode-kubernetes.kubectl-path.mac` are outside the scope of `"vs-kubernetes": { ... }` 

2 enable here are the 2 options:

* Option 1:  If you move those 2 setting under `"vs-kubernetes": {..}` it should help this extension sees correct path of `Kubectl`
* Option 2: If you let `install kubectl` button perform its underlying operation it will set you up with the setting

Another thing I noticed is that we need to update readme which I have done in the PR line below please: 

* https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1133 , deprecated information here: https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/blob/master/package.json#L114

For more thoughts/ideas a gentle ping to @lstocchi , @squillace , @itowlson and @gambtho Thanks heaps ❤️☕️🙏

Thanks heaps.
 
### Here is now replicated

<img width="1056" alt="Screenshot 2022-12-04 at 7 07 05 AM" src="https://user-images.githubusercontent.com/6233295/205470649-2c9ad0d0-75ba-452f-9408-12979597c014.png">

Which lead to 

<img width="608" alt="Screenshot 2022-12-04 at 7 06 56 AM" src="https://user-images.githubusercontent.com/6233295/205470103-d91ac2c8-7e26-44c2-b460-b56ed4bad59e.png">


### Here is default working version

<img width="1055" alt="Screenshot 2022-12-04 at 7 15 03 AM" src="https://user-images.githubusercontent.com/6233295/205470657-53964f6f-9c0f-4da2-a75d-ff94934dfa3d.png">


**Working**

<img width="1217" alt="Screenshot 2022-12-04 at 7 24 58 AM" src="https://user-images.githubusercontent.com/6233295/205470248-770badab-e26d-4a89-9bb6-cf3c5debd995.png">

**Comment by tigerinus** [comment]
@Tatsinnit it is very easy to reproduce. I can reproduct on all my Ubuntu based Linux machine (local, VM, cloud)

**Comment by lstocchi** [comment]
By working on another issue i found out a bug that prevented to retrieve the setting value added using the new field `vscode-ku.....` 😩 #1181 should fixed this issue as well. Sorry for the trouble.

**Comment by tigerinus** [comment]
When is the next release that contains this fix?

**Comment by lstocchi** [comment]
I plan to fix another couple of issues and then make a release. I guess before the end of the next week.
