### ISSUE TITLE
`Unable to parse.` in output tab (Helm)

### ISSUE THREAD

**Issue by iagoalonsomrf** [vscode-kubernetes-tools/vscode-kubernetes-tools#1137]
Kubernetes extension version: `v1.3.11`

VSCode `Help: About` output:

```
Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T03:54:53.913Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.14.0-1054-oem
Sandboxed: No
```

**Comment by jonkyops** [comment]
Happening for windows as well, same symptoms described above:

```
Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
```

Was able to reliably reproduce it by doing this:

1. Open a github codespace on [this repo](https://github.com/helm/examples)
1. Install the Kubernetes extension
1. Make sure the terminal tab is selected in the bottom panel
1. Open charts/hello-world/values.yaml
1. On line 28, enter an invalid character, like `=`
1. Focus in the bottom panel will switch to the Output tab (Helm in the dropdown), and log `Unable to Parse`

**Comment by corneliusroemer** [comment]
It's extremely annoying - I've opened a StackOverflow question for it before I realized that there a multiple open issues (and a PR) discussing this already: https://stackoverflow.com/questions/78496622/how-to-block-a-vs-code-extension-from-opening-output-window-on-every-parse-error
