### ISSUE TITLE
Minikube status not wokring "Failed to get status:..."

### ISSUE THREAD

**Issue by KhASQ** [vscode-kubernetes-tools/vscode-kubernetes-tools#1148]
When I run the command "Kubernetes: Minikube status" I face an error 
`Error getting status Error: Failed to get status: ! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 3.2786046s * Restarting the docker service may improve performance.`

When I try to run `docker container inspect minikube --format={{.State.Status}}` in PowerShell it doesn't work.
But win I run it in cmd it works fine 

How I can solve this issue

**Comment by M00TSDNS** [comment]
The package uses `shelljs` and its unsure if that syntax `{{.State.Status}}` is actually working.
It is definitely running it in cmd per the docs.

One would need to debug by sniffing with breakpoints in VS Code JavaScript Debug Terminal.

**Comment by lstocchi** [comment]
Hi @KhASQ ,
have you tried to run the `Minikube status` command from the shell by using the minikube binary used by the extension?
Do you have something similar to `"vscode-kubernetes.minikube-path.` in your settings.json in vscode? Use the minikube from that path. Which version is it? Does it work?

**Comment by KhASQ** [comment]
Thank you @M00TSDNS and @lstocchi 

I did minikube status from the same minikube in the "vscode-kubernetes.minikube-path"
Using powershell 


`PS C:\kube> .\minikube.exe status
! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 3.3915676s
* Restarting the docker service may improve performance.
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured

PS C:\kube> .\minikube.exe version
minikube version: v1.29.0
commit: ddac20b4b34a9c8c857fc602203b6ba2679794d3`

And this using CMD 


` C:\kube>minikube.exe status
! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 3.3177049s
* Restarting the docker service may improve performance.
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured


C:\kube> minikube.exe version
minikube version: v1.29.0
commit: ddac20b4b34a9c8c857fc602203b6ba2679794d3 `


So the problem from Minikube ?

If yes is there any solution for this

**Comment by lstocchi** [comment]
Hi @KhASQ ,
yes, the kubernetes extension just uses the minikube binary to execute the `status` command so it has nothing to do with it.

There are several issues regarding your problem in the minikube repo. I suggest to give them a try or open a new one yourself. 
Hopefully they will guide you to solve your problem

- https://github.com/kubernetes/minikube/issues/14470
- https://github.com/kubernetes/minikube/issues/7833

**Comment by lstocchi** [comment]
Closing as i think this is related to minikube itself. Feel free to open a new issue if you face some other misbehavior
