### ISSUE TITLE
Debugger in attach mode failing

### ISSUE THREAD

**Issue by pWoLiAn** [vscode-kubernetes-tools/vscode-kubernetes-tools#1156]
![image](https://user-images.githubusercontent.com/49567139/220265153-8fad0c58-2ba1-4853-b396-03100d97bdbe.png)

**Comment by lstocchi** [comment]
This issue is the same as #1184. It should be fixed by https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1185 . Closing it as duplicate. Feel free to reply on the other thread/opened PR. Thank you and sorry for the late response.
