### ISSUE TITLE
Bad CPU in executable

### ISSUE THREAD

**Issue by lukaso** [vscode-kubernetes-tools/vscode-kubernetes-tools#1162]
When syncing settings between different MacOS CPU architectures, the extension cannot determine the correct CPU type. I get this error:

```
Failed to determine minikube version: Error: Error checking for minikube updates: /bin/sh: /Users/user/.vs-kubernetes/tools/minikube/darwin-arm64/minikube: Bad CPU type in executable
```

This is happening on an Intel Mac.

I am syncing my settings from an M1 mac.

**Comment by lstocchi** [comment]
Closing as there was no response. I hope it was solved. Feel free to reopen if you still face any issue. Thanks!!

**Comment by lukaso** [comment]
Sorry. It wasn't solved since my settings are synched across. I don't use the intel Mac very often so that's my workaround.
