### ISSUE TITLE
Kubeconfig location setting

### ISSUE THREAD

**Issue by kferrone** [vscode-kubernetes-tools/vscode-kubernetes-tools#1167]
I have a workspace per customer and each one has its own kubeconfig. I would like to set a workspace specific setting in the settings.json which tells the workspace where the kubeconfig is. 

The current behavior will remember where you set the kubeconfig for every single workspace when you set it. So if I set the cluster to use the kubeconfig for a certain customer, then open another customers workspace, the extension will remember and now both will have the same kubeconfig. When I restart my computer, every single workspace will open using the same kubeconfig which is always what I used last. This means every single friggin time I open a customer workspace, the first thing I need to do is select `set kubeconfig`. 

I had the same issue with the AWS extension and where the aws ini file is located. The solution here was to export the `AWS_CONFIG_FILE` right before opening a workspace. This means I wrote a custom alias to the `code` command which basically does something like `AWS_CONFIG_FILE=${customer}/aws/config code ${customer}.code-workspace.json`

Unfortunately just setting the `KUBECONFIG` variable before running the code command is not honored by this plugin. 
Was hoping this works:  
```sh
AWS_CONFIG_FILE=~/workspaces/${customer}/config/aws \
KUBECONFIG=~/workspaces/${customer}/config/kubeconfig.yaml \
code ~/workspaces/${customer}/${customer}.code-workspace.json
```

**Comment by lstocchi** [comment]
Hi @kferrone , the extension should honor the KUBECONFIG variable if set but it gives precedence to the kubeconfig found in the settings file. Could you please verify you don't have any `vs-kubernetes.kubeconfig` inside your settings.json? If so, can you try removing it and try again? 
If you set the KUBECONFIG in your terminal and launch vscode from there it should work.

Maybe we should support env variables so we can write something like
```
vs-kubernetes.kubeconfig: "path/${customer}/..."
```
and the extension be smart enough to interpret it.

**Comment by kferrone** [comment]
Setting KUBECONFIG like this `KUBECONFIG=... code .` unfortunately does not work for me. 

Where and how do I set this `"vs-kubernetes.kubeconfig"`, I just get a warning it's an unknown setting. I can't search for it in the UI either. 

My `settings.json`
```json
{
  "vs-kubernetes.kubeconfig": "/Users/me/workspaces/someproject/config/kubeconfig.yaml",
}
```

**Comment by lstocchi** [comment]
Which OS are you on? Vscode version? 
Are you sure the settings do not contain any kubeconfig field when starting code, right?
When you launch vscode, if you open the terminal in it and you print the env variable KUBECONFIG value which path it shows?
Below i set the kubeconfig to `/test` and i see the correct value in code terminal.
![image](https://user-images.githubusercontent.com/49404737/232216033-cef560fb-3d73-49a9-91d8-9636b51e7460.png)

If you do the same and the KUBECONFIG value in the terminal is the one you expect (`/test` in my case), when you open the extension, the tree should be empty. Can you confirm it?

**Comment by kferrone** [comment]
MacOS M1 Pro with Ventura 13.3.1
Vscode 1.77.3

First I remove the setting, ie. vs-kubernetes.kubeconfig

I have a function, I mentioned before, which sets the KUBECONFIG variable to correct place as I turn on vscode. 
Like this: `KUBECONFIG=... code .`

I also use `direnv`, this means as I open the terminal it loads the env with KUBECONFIG set to the correct place. 

I try further. Maybe I remove anything setting it per workSpace, ie remove from the function and the direnv and the settings. Now when I echo KUBECONFIG, nothing. Still the cluster is set to what it was in the last workspace. 

Just to see what happens I set the var globally in my profile. Still the same. I have no idea why, but the variable is definitely ignored by vscode on my machine. 

No matter what I do, the only thing which will correctly set the KUBECONFIG location is the `vs-kubernetes.kubeconfig` setting in the workspace settings.

**Comment by kferrone** [comment]
I found out the issue. My user level config also has `vs-kubernetes.kubeconfig`. I guess the user settings take precedence over the variable. When the UI is used it sets `vs-kubernetes.kubeconfig` globally. When changed in one workspace, another will see it because, user level ya know.
