### ISSUE TITLE
Improper YAML Causes Memory Leaks in VSCode

### ISSUE THREAD

**Issue by h3xcat** [vscode-kubernetes-tools/vscode-kubernetes-tools#1170]
An improperly formatted YAML file results in memory leaks when attempting to open it in Visual Studio Code with the Kubernetes extension enabled.

### Test YAML file: (include dashes and dots)
```yaml
---
test: "aaa
...
```

### Error Message:
![](https://files.h3x.cat/o4edvlm19)

**Comment by Tatsinnit** [comment]
💡Thank you so much for this. For wider idea I think this is the issue could be relating to this behaviour (mentioned in link below) and not directly associated with this vscode extension: https://stackoverflow.com/questions/71614897/vscode-crashed-reason-oom-code-536870904

please do add replicating steps so that we can replicate if there is some indication of this extension is the cause please 🙏 

Also, kind cc: @lstocchi + @squillace and @itowlson - for more thoughts or if I missed anything. Thank you so much.

**Comment by h3xcat** [comment]
@Tatsinnit There's not many steps required to replicate, just having the provided yaml code open in vscode with Kubernetes extension enabled is sufficient for memory leak to occur. It happens quite fast and crashes within 10 seconds. 

The memory leak only occurs when the Kubernetes extension is specifically enabled in unrestricted mode.

**Comment by lstocchi** [comment]
Hi @h3xcat, which version of the yaml extension you have? 
are you logged in in a cluster when this happens? What if you log off and try again? 
if you add the directive `# vscode-kubernetes-tools: exclude` at the top of your yaml file what happens?

Basically, to me, this does not seem to be an issue with the yaml file directly. Maybe it triggers something else. 
The directive tells the extension not to provide any schema. It should not happen in any case as the yaml does not contain any kind/apiversion but just to do a test.
Then if you can try it with a cluster and without it to see if it triggers something else, maybe some call. Just throwing ideas on the table as i don't know what it could be atm.

**Comment by h3xcat** [comment]
> which version of the yaml extension you have? 

  redhat.vscode-yaml: v1.12.2
  ms-kubernetes-tools.vscode-kubernetes-tools: v1.3.11

> are you logged in in a cluster when this happens?

  I'm logged in to docker-desktop local kubernetes cluster

> What if you log off and try again?

  Still causes a crash

> if you add the directive `# vscode-kubernetes-tools: exclude` at the top of your yaml file what happens?

  The editor no longer crashes. Removing a single character from directive instantly cause a crash again.

**Comment by lstocchi** [comment]
> The editor no longer crashes. Removing a single character from directive instantly cause a crash again.

Thanks for the quick answer. Atleast we know this is something in our extension. I'll give it a look
