### ISSUE TITLE
Option to switch off Helm

### ISSUE THREAD

**Issue by dsyer** [vscode-kubernetes-tools/vscode-kubernetes-tools#1175]
I don't use Helm, so it isn't installed in my environment. This VSCode extension moans at me constantly "Cannot find Helm binary" and there seems to be no way to switch it off. Am I missing something?

**Comment by lstocchi** [comment]
Hi @dsyer , thanks for letting us know about this problem. We just merged a fix https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1179 . You could set `vs-kubernetes.suppress-helm-not-found-alerts` to true from next release to prevent the warning from appearing again and again. And sorry for the late response.
