### ISSUE TITLE
release frequency

### ISSUE THREAD

**Issue by carljmosca** [vscode-kubernetes-tools/vscode-kubernetes-tools#1183]
I am wondering how frequently this extension might be released.  It seems it's been some time unless I am not looking at the correct source.

TIA,
Carl

**Comment by lstocchi** [comment]
Nobody is working on this project full time, or even part-time i'd say ... it's more when some of us have some spare time, so there isn't an actual release frequency. 

I have been busy on other projects in the last months that prevented me to be active here. Now that i have some time to dedicate to it i'm fixing some issues. I plan to make a new release next week.

**Comment by carljmosca** [comment]
I understand @lstocchi and very much appreciate the efforts.

Regards,
Carl
