### ISSUE TITLE
`Kubernetes` extension disappears after restart vscode every time.

### ISSUE THREAD

**Issue by enihcam** [vscode-kubernetes-tools/vscode-kubernetes-tools#1202]
repo:
1. install `bridge-to-kubernetes` extension
2. popup a window asking for install `Kubernetes` extension, even though `Kubernetes` extension is installed.
3. click `yes` for "reinstall"

then `Kubernetes` extension is removed, and afterwards I install it again, it keeps disappearing everytime i restart vscode.

:(

**Comment by Tatsinnit** [comment]
Thank you so much @enihcam for sharing this information, can you please share the vscode version, and any specific questions x tension version information as well, I will try and recreate this experience from above and loop back with what I found.

**Comment by enihcam** [comment]
no worries. i reinstalled everything and it works fine now.
