### ISSUE TITLE
Golang debug support

### ISSUE THREAD

**Issue by SlavaUtesinov** [vscode-kubernetes-tools/vscode-kubernetes-tools#1225]
Hello!

At your [debug documentation ](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/blob/master/debug-on-kubernetes.md) it is written that golang language has been supported. I installed the latest version of your extension 1.3.15 and at Kubernates: Debug (Attach) command at VS Code I can see only four options: dotnet, java, nodejs and python, what about golang?

Thanks.

**Comment by Tatsinnit** [comment]
Thank you @SlavaUtesinov  for this, not **but** here is what I see, can you please share the steps or screenshot please.

Here is the `go` option which appears in my side. cc: @peterbom  to correct me in case I misunderstood anything as well.

Thank you.

<img width="284" alt="Screenshot 2023-11-06 at 9 53 47 AM" src="https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/assets/6233295/62e328e4-871d-426a-8fd8-90d285aa71ec">

<img width="867" alt="Screenshot 2023-11-06 at 9 53 05 AM" src="https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/assets/6233295/43ef562b-fbfa-40bb-84a0-255fac3c7d16">

**Comment by SlavaUtesinov** [comment]
Hi, @Tatsinnit.
Yes, indeed it works as you showed, it is something arcane. You may close the issue. Thanks.
