### ISSUE TITLE
Kubectl command failed WSL

### ISSUE THREAD

**Issue by fedorzh** [vscode-kubernetes-tools/vscode-kubernetes-tools#1228]
I have standard Windows installation of VSCode, and use it with WSL. I installed kubectl with snap
`sudo snap install kubectl --classic`
when I try to use Kubernetes extension, keep getting error `Kubectl command failed: unable to run kubectl` without any more logs and explanations.
Unfortunately previous solutions https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/522#issuecomment-645940091 do not work for Windows

Related issues: https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/770 https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/771

**Comment by Tatsinnit** [comment]
Thanks a lot, @fedorzh, for bringing this to our attention. If you have anything else specific steps to reproduce the issue, please share them, I can attempt to replicate it this.

We'll look into this and provide an update. Thank you so much.

**Comment by peterbom** [comment]
Hi @fedorzh - I've tried installing `kubectl` with the snap command you shared but haven't been able to replicate the issue.

If you'd be willing to answer a couple more questions, I hope we can get a better idea of what's going wrong:
1. Is the `kubectl` path overridden in Settings?
  <img width="338" alt="image" src="https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/assets/1817696/0d777996-59f6-45d6-9efa-e8ca5cdd553d">

2. Could you run `Developer: Toggle Developer Tools` from the command palette, and try doing anything that causes that error? I'm hoping you might get a message in the Console tab, something like `*** failed to invoke kubectl (from ...)`, which might give us more information.

**Comment by fedorzh** [comment]
@peterbom so I removed `kubectl` from `snap ` and installed with vscode after the extension installation, in the interface. This error disappeared and now I get a different problem not connected to this one
