### ISSUE TITLE
Maintenance: Enable Dependabot, stocktake the required packages.

### ISSUE THREAD

**Issue by Tatsinnit** [vscode-kubernetes-tools/vscode-kubernetes-tools#1276]
Thank you all who contribute, I open this issue to track and remove the unwanted, unnecessary aspect of this code base which might not be required for the package update and general health of this repo. ❤️🙏

Few things like:

* Enabling Dependabot.
* Enable security scanning. 
* Remove any half baked code/code gardening et. al. 

Update: I am currently doing this against my fork and will open the PR once I have decent drop, I see there are over 41 security alerts which we should cater. A specific area which is never developed was the `site` so I might remove it moving forwards and tag folks if anyone had any idea for the reasons et. al. Thank you so much.

Opening this as FYI. @squillace , @gambtho , @qpetraroia, @hsubramanianaks

Thanks all.

**Comment by qpetraroia** [comment]
Ack on this. Thank you @Tatsinnit for maintaining this CNCF project!

**Comment by Tatsinnit** [comment]
❤️ Closing this now, this is all taken care of now, please refer to the PRs above which are linked. Thank you so much.
