### ISSUE TITLE
Error in windows with new release: 1.3.17

### ISSUE THREAD

**Issue by Tatsinnit** [vscode-kubernetes-tools/vscode-kubernetes-tools#1354]
Hiya All, Apologies for the inconvenience! It seems the latest vsix release introduced as bug in windows related ~to `suppress-output`, which is affecting multiple machines and extension health. Just wanted to give a heads-up to @okgolove in case you’ve encountered this. Thank you!~

### Update - 10th October - This is fixed please refer to details in here and reason: https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1355#issue-2574644066 Thank you so much ❤️ 

~**Update**: It looks like this might be related to how `this.channel` is being set. I’m currently debugging the hook in the older code and considering a middle-ground solution if the issue turns out to be too deep. I came across an old reference that might shed some light: https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/907#issuecomment-819224756.~

~You can also take a look at this pull request for more context:  
https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1208/files.~

**The behavior**:  Error: `There is no data provider registered that can provide view data.`

Interestingly, I’ve tried this on my Mac, and it works fine there, but the issue is consistently showing up on Windows. I’m currently working on a temporary fix as recommended below, but if anyone else wants to jump in and help, you’re more than welcome!

~As a moving forward solution, please read detail in this: https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1355~

Thanks so much for your understanding and support!

![image](https://github.com/user-attachments/assets/cceccbc4-3979-4747-9770-8c172d95fe32)

**Comment by kejatura-dev** [comment]
+1 Can confirm this is happening to me too:

![image](https://github.com/user-attachments/assets/33c7ee3b-05e0-4fe1-b672-297473fa08f1)

**Comment by AlexanderSysoiev** [comment]
As a temp fix we had to roll back to the prev version:
![image](https://github.com/user-attachments/assets/b4855ae8-e50c-4fbf-98f4-c4b0febef99c)

**Comment by vonchenplus** [comment]
+1 Can confirm this is happening to me too

**Comment by mauriciocirelli** [comment]
+1 
Having the same issue here with 1.3.17.
Downgrading to 1.3.16 works.

**Comment by metaphy6** [comment]
I got the same error:

`Error running command extension.vsKubernetesRefreshExplorer: command 'extension.vsKubernetesRefreshExplorer' not found. This is likely caused by the extension that contributes extension.vsKubernetesRefreshExplorer.`

**Comment by verhelstq** [comment]
Same, here rolled back to version 1.3.16
