### ISSUE TITLE
Error with existing connections in VS Code Add-On

### ISSUE THREAD

**Issue by datherton-hr** [vscode-kubernetes-tools/vscode-kubernetes-tools#1356]
Receiving following error using updated version 1.3.17:
Error running command extension.vsKubernetesCreateCluster: command 'extension.vsKubernetesCreateCluster' not found. This is likely caused by the extension that contributes extension.vsKubernetesCreateCluster.
![image](https://github.com/user-attachments/assets/d62a4a3a-523e-47e3-9c82-67d93ae4dee2)

Existing connections were not loaded but once reverted back to 1.3.16, it started working.

**Comment by hsubramanianaks** [comment]
@datherton-hr Thanks for opening this, we already have an issue open for extension not working in windows. https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1354. 
we will have a fix with release soon. Until then you can always revert to previous version. Thanks for the patience.

**Comment by Tatsinnit** [comment]
##Update:

Thank you @datherton-hr and @hsubramanianaks,  Please try out our latest release `1.3.18` which fixes this issue. also fyi : https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1354#issuecomment-2403679387
