### ISSUE TITLE
Deprecate clipboardy and find replacement

### ISSUE THREAD

**Issue by hsubramanianaks** [vscode-kubernetes-tools/vscode-kubernetes-tools#1357]
With Recent release version 1.3.17 , we had an issue with extension not loading properly
read more about it #1355 @Tatsinnit FYIP
screenshot:
![image](https://github.com/user-attachments/assets/5e64458f-7a92-4ba7-b3dc-37163b8cfbdd)

It was due to following error from one of the dependency - clipboardy not converting the url path's based on the platform/os.
TypeError: File URL path must be absolute
	at getPathFromURLWin32 (node:internal/url:1433:11)
	at fileURLToPath (node:internal/url:1466:35)

so we have to find a replacement for this dependency which is maintained.

**Comment by Tatsinnit** [comment]
💡 Totally sounds like a good idea. I think it has minimalist usage given last stable release was 4 years ago we should move to something in-house. Thanks heaps. ❤️

**Comment by Moazzem-Hossain-pixel** [comment]
Help me to get
