### ISSUE TITLE
Error running command kubernetes.cloudExplorer.findProviders: command 'kubernetes.cloudExplorer.findProviders' not found

### ISSUE THREAD

**Issue by manasij12** [vscode-kubernetes-tools/vscode-kubernetes-tools#1358]
Error running command kubernetes.cloudExplorer.findProviders: command 'kubernetes.cloudExplorer.findProviders' not found. This is likely caused by the extension that contributes kubernetes.cloudExplorer.findProviders.

Version: 1.94.1 (user setup)
Commit: e10f2369d0d9614a452462f2e01cdc4aa9486296
Date: 2024-10-05T05:44:32.189Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26100

![image](https://github.com/user-attachments/assets/a57b663a-b57f-429e-ba79-1db6488ec829)

![image](https://github.com/user-attachments/assets/c7321f30-d925-4fa4-a14c-1447a3542b00)

Tried re-installating the VSCode after clearing all the user data from : %APPDATA%\Code and %USERPROFILE%\.vscode.
And multiple reboots, does not help
Also re-installing the extensions.

Please suggest fix

**Comment by Tatsinnit** [comment]
Thanks @manasij12 for reporting this, we have fixed the problem and will be taking this to release soon, more details can be read under #1354  and #1355 , Thank you ❤️

**Comment by Tatsinnit** [comment]
##Update:

Please try out our latest release `1.3.18` which fixes this issue. also fyi : https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1354#issuecomment-2403679387
