### ISSUE TITLE
problem on showing log of init container

### ISSUE THREAD

**Issue by lcasavola** [vscode-kubernetes-tools/vscode-kubernetes-tools#1373]
Hello,
with v.1.3.18 when i try to get log from a init container i got the following error ( more evident by using the Termina destination)
 kubectl logs pod/omnis11v2-684f969958-45wp6 --namespace=omnis-bas-001 --container=logshipper (init) -f --since=0
bash: syntax error near unexpected token `('
I think the problem is due to the fact that the container list box present the suffix "(init)" for the init container and that suffix is not excluded when you generate thecontainer name on  kubectl log command.
 IN the previous version the log for init container worked correctly.
Rgds
Luca

**Comment by hime** [comment]
Having the same issue.

**Comment by bcmyguest** [comment]
@Tatsinnit feel free to change my PR, I can be slow to reply on this account

**Comment by hime** [comment]
Do we know what release contains this fix?

**Comment by bcmyguest** [comment]
@hime No release yet :(
