### ISSUE TITLE
Fake error message "add existing cluster"

### ISSUE THREAD

**Issue by sallyur** [vscode-kubernetes-tools/vscode-kubernetes-tools#227]
Build: 4623

When I tried to add a k8s cluster, I got the following error at the end:

![image](https://user-images.githubusercontent.com/28860891/40833109-8942aea8-65bf-11e8-8204-369968cde355.png)

But later I tried to see whether the new cluster is added, I successfully configured the cluster to my local registry. And I can operate on the nodes:

![image](https://user-images.githubusercontent.com/28860891/40833159-aaba500e-65bf-11e8-90ca-4d626d18dfb0.png)

**Comment by itowlson** [comment]
This works because `kubectl` is already installed (possibly even in that very location).  We should skip downloading `kubectl` if you already have a working `kubectl`.

**Comment by brendandburns** [comment]
@itowlson i think this is fixed, right?

**Comment by itowlson** [comment]
@brendandburns The error Sally reported is transient as far as we know so there's nothing to fix on that side.  We haven't done anything about skipping downloading `kubectl` though.  We can probably close this as the latter is an optimisation we could raise as a separate issue, though Sally has a point that it's a confusing failure mode!

**Comment by Tatsinnit** [comment]
Thank you so much for this issue, I tried this by completely nuking and retrying to download this extension and seems like it is no-longer an issue. 

Given this was open for long, I will close this for now and if there is anything missed please feel free to re-open it. Thank you. cc: @squillace , @lstocchi and @itowlson as fyi. Thank you.
