### ISSUE TITLE
Build and publish extension artifacts from pull requests to GitHub

### ISSUE THREAD

**Issue by bnookala** [vscode-kubernetes-tools/vscode-kubernetes-tools#262]
Use ACR Build (or something else!) to build the extension from pull requests, and publish a downloadable vsix, making it easier for us to test.

**Comment by radu-matei** [comment]
I would suggest Brigade!

Brigade is already using Brigade to run tests, build binaries, upload them to GitHub releases (this is the [actual `brigade.js` file that builds Brigade](https://github.com/Azure/brigade/blob/master/brigade.js))

**Comment by Tatsinnit** [comment]
Thank you so much for this, we have enabled the Github action for this purpose int his repo - `build and publish` and we are for almost a year now publish that using `on-click` deploy functionality. `vsix` artefacts are also part of the publish release notes, closing this issue for now. Please feel free to re-open with more detail in case I missed anything. cc and fyi: @squillace , @lstocchi and @itowlson thank you
