### ISSUE TITLE
Expose VSCode command for picking a Kubernetes Pod

### ISSUE THREAD

**Issue by loligans** [vscode-kubernetes-tools/vscode-kubernetes-tools#745]
It would be nice if a vscode command was exposed to pick the minikube pod.

Something like: `${command:extension.vsKubernetes.pods}`

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach Api (Kubernetes)",
            "type": "coreclr",
            "request": "attach",
            "pipeTransport": {
                "pipeProgram": "kubectl",
                "pipeArgs": [ "exec", "-i", "${command:extension.vsKubernetes.pods}", "--" ],
                "pipeCwd": "${workspaceRoot}",
                "debuggerPath": "/vsdbg/vsdbg",
                "quoteArgs": false
            },
            "processId": "${command:pickRemoteProcess}",
            "sourceFileMap": {
                "/src": "${workspaceRoot}/src",
                "/app": "${workspaceRoot}/src/Loligans.Api"
            }
        }
    ]
}
```

**Comment by itowlson** [comment]
This is really interesting.  How do you see the user experience here - is it interactive?  E.g. the command displays a popup listing all (?) pods in the current namespace, and then returns the selected one (or undefined if the user cancelled)?

**Comment by loligans** [comment]
@itowlson I envision it similar to how the existing `Kubernetes: Debug (Attach)` functionality works. It would present itself when the user chooses to start a Debug session.

![image](https://user-images.githubusercontent.com/3218210/80456187-05d43080-88e2-11ea-965f-07639ab87892.png)


The user simply chooses a `pod` and it populates the `launch.json` field. If they cancel the operation ideally it would cancel the launch, however supplying an empty string may be sufficient enough.

**Comment by loligans** [comment]
It seems like this bit of code would need to be turned into a command: https://github.com/Azure/vscode-kubernetes-tools/blob/50bedbff92dca38bb8c6aefe4aca0e3f9c9005e2/src/debug/debugSession.ts#L209-L239

**Comment by SethFalco** [comment]
Just a heads-up, looks like this issue can be closed?

Looks like it's fixed by:
* https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1017

**Comment by itowlson** [comment]
Good catch, thank you @SethFalco
