### ISSUE TITLE
Orphaned kubectl.exe processes on Windows

### ISSUE THREAD

**Issue by philomory** [vscode-kubernetes-tools/vscode-kubernetes-tools#769]
# Description
For each VS Code window, the first time you open a YAML file, a bunch of `kubectl` processes spawn; most of them quickly exit again, but one (invoked as `"C:\ProgramData\chocolatey\lib\kubernetes-cli\tools\kubernetes\client\bin\kubectl.exe" proxy --port=0"`) persists. In fact, it persists even after the associated VS Code window has been closed, and indeed after all vscode processes have exited. 

If the VSCode windows were project windows (rather than directly opened to individual files), then additionally each `kubectl` process is run from the project directory of the window it was spawned from, which on Windows prevents various operations like renaming or deleting said directory until the kubectl process is killed.

# Steps to reproduce:

1. Install the Kubernetes extension in Visual Studio Code
2. Open any YAML file
3. Open a new window
4. In the new window, open another YAML file
5. Close all Visual Studio Code windows and processes
6. Observe that two running instances of `kubectl proxy --port=0` remain

# Environment:
## Visual Studio Code
Version: 1.46.0 (user setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

## Kubernetes Extension
1.2.1

## Kubectl
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by itowlson** [comment]
Thanks for flagging this - we'll take a look.

**Comment by SayakMukhopadhyay** [comment]
I am seeing this issue too. It has an additional side effect of locking the folders in which the kubectl is spawed which means I can't delete it anymore. Right now, deleting all kubectl processes manually fixes these issues.

**Comment by vasily-codefresh** [comment]
Same problem here, I noticed it back in November when I installed Kubernetes extension.
Now it's still pronounced with VSCode 1.49.0, Kubernetes plugin 1.2.1 and any kubectl from 1.14 to 1.19.

**Comment by cronventis** [comment]
This is still the case.

And for me, since I'm not using the kubectl command at all in the terminal, I would like to be able to disable the kubectl usage.

**Comment by knoxi** [comment]
Same problem here.
And since the process is running in the scope of the loaded workspace folder, the folder cannot be removed after closing VS Code because the process locks the folder. You need to kill the process to remove the folder.

**Comment by chillum** [comment]
somehow the fix doesn't work (as of 1.74.3), and exiting vscode doesn't kill spawned `kubectl.exe` processes. it does kill some in a while after exit, but not the all, the rest are hanging forever:

```powershell
~ % ps|sls kubectl
~ % code -w
~ % ps|sls kubectl

System.Diagnostics.Process (kubectl)
System.Diagnostics.Process (kubectl)
System.Diagnostics.Process (kubectl)
System.Diagnostics.Process (kubectl)
System.Diagnostics.Process (kubectl)

~ % sleep 60
~ % ps|sls kubectl

System.Diagnostics.Process (kubectl)
System.Diagnostics.Process (kubectl)

~ % 
```

**Comment by jheiselman** [comment]
Still an issue for me too.

VS Code Info
Version: 1.81.1 (system setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z (3 wks ago)
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

Extension Info
Version: v1.3.13

Kubectl Info
Version: 1.21.1

**Comment by zeko77** [comment]
Still an issue 1.87.2
