### ISSUE TITLE
How can I use context setting instead cluster?

### ISSUE THREAD

**Issue by yoyoys** [vscode-kubernetes-tools/vscode-kubernetes-tools#789]
My AWS EKS cluster required different user between clusters.
If this plugin couldn't select context or user for the cluster, only default context available.

**Comment by lstocchi** [comment]
I'm not sure i got what's the problem here, but it looks to me you are not able to switch in different clusters using different users, right? Couldn't you create different contexts (each one with a specific user/cluster) in your kubeconfig and use them to switch by using the extension?
