### ISSUE TITLE
UX: Status bar select namespace should directly show the list of available namespaces

### ISSUE THREAD

**Issue by sandipchitale** [vscode-kubernetes-tools/vscode-kubernetes-tools#956]
Clicking on current namespace name in status bar should show the (second) prompt which shows the list of available namespaces. 

Why show the first prompt which asks user to type the name of the namespace - which is possible to be typed in the second prompt anyway - which nicely works as a filter.

I understand the current implementation may have been done for performance reasons and for good typists.

**Comment by sandipchitale** [comment]
.

**Comment by lstocchi** [comment]
Hi @sandipchitale, thanks for opening this and sorry for the really late response. We are few and also busy on other projects. 
I remember that we made a similar change for another command and the original workflow (first step -> second step) can be re-enabled by a setting or viceversa. I guess we can do the same here, so users can decide the behavior they prefer.
And you're right, the current implementation was made for performance reasons. I'll propose a PR asap. Thanks for your patience!

**Comment by sandipchitale** [comment]
@lstocchi Oh thanks you. Looking forward to PR getting into the extension.
