### ISSUE TITLE
Helm 3 is not recognized

### ISSUE THREAD

**Issue by johnbendi** [vscode-kubernetes-tools/vscode-kubernetes-tools#976]
It seems the tool does not recognize the latest helm version and it's api changes as it's still looking for repositories in the wrong location at `$HOME/.helm/repository/repositories.yaml`

**Comment by bacongobbler** [comment]
ping.

**Comment by dessite** [comment]
Same issue for me
```
helm env
HELM_BIN="helm"
HELM_CACHE_HOME="/home/barry/.cache/helm"
HELM_CONFIG_HOME="/home/barry/.config/helm"
HELM_DATA_HOME="/home/barry/.local/share/helm"
HELM_DEBUG="false"
HELM_KUBEAPISERVER=""
HELM_KUBEASGROUPS=""
HELM_KUBEASUSER=""
HELM_KUBECAFILE=""
HELM_KUBECONTEXT=""
HELM_KUBETOKEN=""
HELM_MAX_HISTORY="10"
HELM_NAMESPACE="default"
HELM_PLUGINS="/home/barry/.local/share/helm/plugins"
HELM_REGISTRY_CONFIG="/home/barry/.config/helm/registry.json"
HELM_REPOSITORY_CACHE="/home/barry/.cache/helm/repository"
HELM_REPOSITORY_CONFIG="/home/barry/.config/helm/repositories.yaml"
```

Yet the extension does not see repos
![image](https://user-images.githubusercontent.com/8626322/136361608-848b0b1f-6519-4f0f-a755-f2e468eb790d.png)

![image](https://user-images.githubusercontent.com/8626322/136361638-23a22d70-69da-4f8d-921e-8eb8dcfcadf6.png)

**Comment by itowlson** [comment]
Sorry for the delay in following up on this.  As @bacongobbler says, the mention of Tiller sounds very much like Helm 2.  I'm wondering if there's a copy of Helm 2 that the extension is inadvertently configured to point to that's different from the one in your shell.  Could you run the extension Helm Version command and let us know what you see?

(If that shows version 2 then check your VS Code extension settings to see if they point to an unexpected/unwanted path.)

**Comment by dessite** [comment]
@itowlson apparently the issue was that in setting UI path was correct but in json it was reffering to `$HOME/.vs-kubernetes/tools` paths, when I was checking at that time UI showed no issues but today when I checked I got
![image](https://user-images.githubusercontent.com/8626322/149782865-07df6aa6-6aea-47b0-be17-f08a3a49cdce.png)
So it seems that now it's working for me, thanks for good pointers.

**Comment by itowlson** [comment]
Great, glad to hear it's working now.  I'll close this - @johnbendi if this doesn't fix it for you then please re-open.
