### ISSUE TITLE
Error: kubectl not found

### ISSUE THREAD

**Issue by chrismason** [vscode-kubernetes-tools/vscode-kubernetes-tools#979]
System Information:
- MacOS: 10.15.7
- VSCode: 1.60.0
- Kubernetes Extension: v1.3.3

Recently I started having an issue where the extension cannot find `kubectl` on VSCode launch. I get an error saying
> Kubectl command failed: kubectl not found

In my settings, I have tried setting both `vscode-kubernetes.kubectl-path` as well as `vscode-kubernetes.kubectl-path.mac` to a specific path and it is giving the same error. E.g.
```
"vscode-kubernetes.kubectl-path": "/usr/local/bin/kubectl"
```
And `/usr/local/bin/kubectl` is the same path I get when I run `which kubectl`

I am using settings sync but this particular setting is ignored so nothing should be stepping on top of it.

I have also not been able to find any specific logs for this extension loading but not sure if I am looking in the correct place or not.

In addition, I have installed kubectl to the local default directory used by the extension at `~/.vs-kubernetes/tools` as well but that has not fixed the issue.

**Comment by bacongobbler** [comment]
Just to confirm... This is how your settings file looks like at the moment, right?

```
 "vs-kubernetes": {
    "vs-kubernetes.kubectl-path": "/usr/local/bin/kubectl"
}
```

Note that `vs-kubernetes` needs to be noted twice in the document.

**Comment by chrismason** [comment]
Correct, there are actually 2 entires in there, not sure which one is the proper one. e.g.
```
"vs-kubernetes": {
       ...
       "vs-kubernetes.kubectl-path.mac": "/usr/local/bin/kubectl",
        "vscode-kubernetes.kubectl-path.mac": "/usr/loca/bin/kubectl"
    },
```

I am not seeing anything specific in the path that might be causing issues and looks how I would expect it to look

**Comment by Bafff** [comment]
"vscode-kubernetes.kubectl-path.mac": "/usr/**loca**/bin/kubectl" maybe because of this?

**Comment by chrismason** [comment]
Any idea where the `vscode-kubernetes.kubectl-path.mac` setting may be coming from?

**Comment by SMFloris** [comment]
We are having the same issue when using microk8s as well.

For example, in theory it would be enough to point it to the kubectl path:

```
"vscode-kubernetes.kubectl-path": "/var/lib/snapd/snap/bin/microk8s.kubectl",
```

But this fails since it expects the binary itself to be named `kubectl` and does not accept anything else which defeats the purpose of the path variable.

**Comment by hcguersoy** [comment]
- OS: macOS 12.4 / ARM
- `kubectl` installed via Homebrew, path is `/opt/homebrew/bin/kubectl`
- Extension version v1.3.10

VSCode respective the extension complained about missing kubectl. My `settings.json` looked like this:

```json
    "vscode-kubernetes.helm-path": "/opt/homebrew/bin/helm",
    "vscode-kubernetes.kubectl-path.mac": "/opt/homebrew/bin/kubectl",
    "vs-kubernetes": {
        "vs-kubernetes.namespace": "",
        "vs-kubernetes.kubectl-path": "",
        "vs-kubernetes.helm-path": "",
        "vs-kubernetes.minikube-path": "",
        
    },
```  

`vscode-kubernetes.kubectl-path` was missing, `vs-kubernetes.kubectl-path` is empty, even I've entered the according path into the extension settings page.
Obviously, `vscode-kubernetes.kubectl-path.mac` is ignored and the other entries are not adopted into the json file. 

So I added additional line to the json:

```json
"vscode-kubernetes.kubectl-path": "/opt/homebrew/bin/kubectl",
```

and it's OK now.

**Comment by onelaview** [comment]
- OS: macOS 12.6 / ARM
- `kubectl` installed via Homebrew at `/opt/homebrew/bin/kubectl` and is on system PATH.
- Extension version v1.3.10

Found similar issue. I've got this error notification when opening kubeconfig file (i.e. `/Users/foo/.kube/config`) in my vscode.

![image](https://user-images.githubusercontent.com/512696/201188625-a638908f-2a10-492a-8227-9e3f808183d1.png)

In my case, I don't have `vs-kubernetes.kubectl-path` or `vscode-kubernetes.kubectl-path` settings whatsoever. Only related extension setting is

```
"vs-kubernetes": {
    "vscode-kubernetes.minikube-path.mac": "/Users/foo/.vs-kubernetes/tools/minikube/darwin-amd64/minikube"
},
```

I solved this by deleting `~/.vs-kubernetes` folder, uninstall the extension and then re-install it. Now the error notification doesn't popup anymore.

**Comment by rahulspoudel** [comment]
> * OS: macOS 12.6 / ARM
> * `kubectl` installed via Homebrew at `/opt/homebrew/bin/kubectl` and is on system PATH.
> * Extension version v1.3.10
> 
> Found similar issue. I've got this error notification when opening kubeconfig file (i.e. `/Users/foo/.kube/config`) in my vscode.
> 
> ![image](https://user-images.githubusercontent.com/512696/201188625-a638908f-2a10-492a-8227-9e3f808183d1.png)
> 
> In my case, I don't have `vs-kubernetes.kubectl-path` or `vscode-kubernetes.kubectl-path` settings whatsoever. Only related extension setting is
> 
> ```
> "vs-kubernetes": {
>     "vscode-kubernetes.minikube-path.mac": "/Users/foo/.vs-kubernetes/tools/minikube/darwin-amd64/minikube"
> },
> ```
> 
> I solved this by deleting `~/.vs-kubernetes` folder, uninstall the extension and then re-install it. Now the error notification doesn't popup anymore.

This worked for me too. Thanks buddy. It was getting really annoying.
