### ISSUE TITLE
[Feature request] Support namespace selector

### ISSUE THREAD

**Issue by olljanat** [vscode-kubernetes-tools/vscode-kubernetes-tools#982]
Shared multi-tenant/multi-application clusters can easily contain hundreds of namespaces which makes using this extension hard. 

Most of the users however are working with one/couple of application(s) which why it would be very useful to have support for filtering those. Kubernetes RBAC does not and will not support that at least on near future https://github.com/kubernetes/kubernetes/issues/56582 so it need to be handled on client side.

What I would like to see here is support for namespace selector label which would be then passed to `--selector` parameter on 
https://github.com/Azure/vscode-kubernetes-tools/blob/336a9ec500a31781f3c02a152c8ef85377d03cec/src/kubectlUtils.ts#L202-L203

So example in case recommended labels https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/ are used then user would be able to define selector value `app.kubernetes.io/name=mysql` and then this extension would be using command like this to get list of namespaces:
```
kubectl get namespaces --selector app.kubernetes.io/name=mysql -o json
```

**Comment by gnunn1** [comment]
I was going to open a new feature request for an idea which addresses this issue but I think it would make sense to include it here. 

As noted in this issue the extension isn't very useable when the context has hundreds of clusters/users/namespaces as finding the right context to open is difficult. Additionally switching quickly between two namespaces, say dev and qa namespaces to troubleshoot, is is challenging as well. IMHO the extension should be hiding the intricacies of the kube context from the user and providing a simplified view. 

At the moment the extension displays the list of contexts by `namespace/cluster/user` and the user selects the appropriate context and goes from there. My suggestion is that the extension display only the cluster/user in the top level list and omits the namespace which would collapse the list to a much more manageable size. To handle the namespace switching we leverage the existing Namespaces sub item and display one of two things:

1. If the user has access to the namespace API (i.e. cluster-admin) display all namespaces
2. If the user does not have access to the namespace API display a list of namespaces from the kube context for the currently selected cluster/user

Similar to OpenShift Projects, a menu item or other more intuitive UI element can be provided to enable the user to select the currently active namespace. When the namespace is selected the extension either uses an existing context or in the case of a cluster-admin user selecting a new namespace generates a new one via kubectl or oc. The currently selected namespace would be displayed prominently at the root level item.

From my point of view this makes the extension much easier to navigate while abstracting away some of the complexities of the kube context for newer users.

**Comment by olljanat** [comment]
Definitely it make sense try find common solution. However some comments to these:

> To handle the namespace switching we leverage the existing Namespaces sub item and display one of two things:
> 
> 1. If the user has access to the namespace API (i.e. cluster-admin) display all namespaces
> 2. If the user does not have access to the namespace API display a list of namespaces from the kube context for the currently selected cluster/user

We need combination of these like it was on original request where user have permission to list all namespaces but access to only some of them which why there need to be some kind of filtering feature.

Example in case fully dynamic environments where namespace(s) gets automatically created for each pull request (and removed after those are completed) manually adding/updating context for those is not usable solution.

**Comment by itowlson** [comment]
@olljanat Can we elaborate a bit more on how a namespace filter/selector would work?  Do you see that as being something that the user configures statically and only changes occasionally (e.g. the settings file), or something that is quite interactive (e.g. the user does a right-click > filter, or gets prompted).

It sounds like you're using the namespaces tree more heavily than we normally see - resources in the active namespace are already displayed directly in the tree.  What is your usage pattern e.g.

* are you working in multiple namespaces at once (i.e. needing to see the contents of namespaces side by side)?
* or is it more that you switch namespace multiple times a day (but while you are in a particular namespace that's the only one you care about)?

@gnunn1 Luca has a PR for an alternative presentation of the tree that focuses far more on the _current_ scope, and relegates other contexts/namespaces to a 'Other...' folder that is used (primarily? only?) for switching.

That said... I don't think we display the tree by `namespace/cluster/user`.  The grouping is `cluster > category > type` e.g. `mycluster > Workloads > Deployments`.  Namespaces are only shown at that category level.

@ollljanat Agree that making that aware of whether the user can access the namespace would be good.

**Comment by olljanat** [comment]
> @olljanat Can we elaborate a bit more on how a namespace filter/selector would work? Do you see that as being something that the user configures statically and only changes occasionally (e.g. the settings file), or something that is quite interactive (e.g. the user does a right-click > filter, or gets prompted).

I was thinking about right-click > filter.

> It sounds like you're using the namespaces tree more heavily than we normally see - resources in the active namespace are already displayed directly in the tree. What is your usage pattern e.g.
> 
>    * are you working in multiple namespaces at once (i.e. needing to see the contents of namespaces side by side)?
>
>    * or is it more that you switch namespace multiple times a day (but while you are in a particular namespace that's the only one you care about)?

I would assume that anyone who is using https://github.com/kubernetes-sigs/hierarchical-namespaces will end up to have a lot of namespaces.

However I actually ended switching to [vcluster](https://www.vcluster.com/) way of implementing multi-tenancy so I don't have big need for this one anymore and as there is no any 👍 reactions on my original message I propose that we close this request.
