### ISSUE TITLE
Extension is "leaking" kubectl processes after vscode closes

### ISSUE THREAD

**Issue by bruno-brant** [vscode-kubernetes-tools/vscode-kubernetes-tools#997]
I'm using this extension as it's a dependency for _Bridge to Kubernetes_. It my current environment, whenever I close vscode, a kubeclt process is left running pointing to the workspace folder. From what I could gather, the command it's running is "proxy".

The expected behavior is to close any child processes when vscode is closed.

----
Environment:

Version:          Code - Insiders 1.63.0-insider (a7104f13ff61bcd9f4c827d8fe3c0d27bb479fd8, 2021-11-08T05:14:49.440Z)
OS Version:       Windows_NT x64 10.0.19044
Extension version: v1.3.3

**Comment by lstocchi** [comment]
Hi @bruno-brant , thanks for opening this. Can you please describe what you do exactly to replicate it? I was able to verify the problem you are mentioning (leaking kubectl processes) with the `port-forward` action but not by using `Bridge to Kubernetes`. It would be helpful to replicate your use case as well. Thank you!

**Comment by bruno-brant** [comment]
Hey @lstocchi, thanks for the follow-up! I'm not exactly sure if the culprit is Bridge or if it's the Kubernetes extension itself, but  it seems to happen more frequently when I'm running Bridge. I'll try to reproduce it more exactly and update the issue.

**Comment by adleatherwood** [comment]
This is still happening.  I have both the `Kubernetes` and the `Bridge to Kubernetes` extensions installed.  The "bridge" extension is disabled and I have no other K8s-related extensions installed.  I can open up any project with the `Kubernetes` extension install and a `kubectl` process will spawn.  When I close VsCode, the process stays every time.  The type of project doesn't seem to matter at all.  I discovered this because that uncontained `kubectl` process keeps my project directories lock and I can't delete old project etc from windows explorer.

**Comment by itowlson** [comment]
That sounds frustrating - that directory locking thing is a colossal pain!  Could you try using Process Explorer (or similar tool) to find out the full command line - specifically the subcommand/arguments - of the leaked `kubectl` instance please?  That will help us to narrow down where the leaked process is coming from.  Thanks!

**Comment by lstocchi** [comment]
@itowlson Maybe we should merge https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1001 even if it doesn't kill all kubectl processes. I'll try to see again why the observable doesn't work but that should be a good start.

**Comment by sandipchitale** [comment]
@itowlson The complete subcommand/arguments on Windows is:

```
....\bin\kubectl.exe" proxy --port=0
```

And yes, not being able to delete the folders because of this is sometimes puzzling and definitely frustrating when it happens.

I have written the following Doskey macros (aliases) to kill all ```kubectl.exe``` processes (use ```kkc``` alias carefully as it may kill legitimate ```kubectl.exe``` processes):

```
kkc=taskkill /F /IM kubectl.exe
lkc=tasklist /v /nh /fi "IMAGENAME eq kubectl.exe"
```

**Comment by sandipchitale** [comment]
This extension may help until this issue is fixed: 

https://marketplace.visualstudio.com/items?itemName=sandipchitale.vscode-kubernetes-kubectl-ripper

**Comment by mikeseese** [comment]
@lstocchi looking over #1001, one would expect it to work. I proceeded to add `"SIGKILL"` signals to all the calls to `.kill()`, but alas I was still having issues. I eventually realized that `kubectl proxy --port=0` is spawning a new process`~/.kuberlr/windows-amd64/kubectl1.62.0.exe proxy--port=0`. The first process does get killed as expected, but the second lingers. https://github.com/flavio/kuberlr seems to be a kubectl version manager, which is used by Rancher Desktop (which is what I use). Looking in Process Explorer, the second process doesn't seem to be attached to a tree at all, so it's not like killing the first process could even kill the child process.

I'm not sure if this is even within scope of this extension to handle (i.e. if there is some workaround), but I'm leaning on it's not. It is fairly frustrating, but I believe @sandipchitale's extension may solve my usecase

**Comment by mikeseese** [comment]
Actually, changing `proxy.ts:26` to `const dispose = () => { treeKill(proxyingProcess.childProcess.pid, 'SIGKILL'); };` using the https://www.npmjs.com/package/tree-kill does kill both processes. It seems to just be a wrapper around `taskkill` for windows to kill the whole tree: https://github.com/pkrumins/node-tree-kill/blob/master/index.js#L28-L49

@lstocchi would you be opposed to a PR that introduces this dependency (or separately, copies the contents of that module into this project to use) and replace the `childProcess.kill()` calls with `treeKill(childProcess.pid)`?

**Comment by lstocchi** [comment]
@mikeseese if it works i'm all in with this solution. 
Thank you very much for your help!!
